version: "3.8"

networks:
  database:

services:
  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - database

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - database

  mysql:
    container_name: mysql
    image: mysql:8
    volumes:
      - ./volumes/mysql/:/var/lib/mysql/
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: road-to-carnival
      MYSQL_ROOT_PASSWORD: $DB_PASS
    networks:
      - database

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 5002:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - database
